- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(b7628aa8-705c-40f0-bbee-a9bde27419ec)'
    appType: 'webAppLinux'
    appName: 'ludo-capital-api'
    deployToSlotOrASE: true
    resourceGroupName: 'ludo_capital'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.10'